### ISSUE TITLE
Google Sheet to EWB for review

### ISSUE THREAD

**Issue by EWB** [EWB/adk-postcards#2]

**Comment by phaggett** [comment]
So here is the URL for the google spreadsheet.  https://stlawu-my.sharepoint.com/personal/ewilliamsbergen_stlawu_edu/_layouts/15/WopiFrame.aspx?sourcedoc={8BFD0395-9F1A-4CC0-9F58-E844D809C517}&file=postcard-metadata-special-collections.xlsx&action=default

**Comment by phaggett** [comment]
So...I think I went ahead and closed this when you told me not to...my bad.  Here is the link again:  https://stlawu-my.sharepoint.com/personal/ewilliamsbergen_stlawu_edu/_layouts/15/WopiFrame.aspx?sourcedoc={8BFD0395-9F1A-4CC0-9F58-E844D809C517}&file=postcard-metadata-special-collections.xlsx&action=default
